name: kheera-frontend-dev

services:
  kheera-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: kheera-frontend-dev

    restart: unless-stopped

    ports:
      - '4201:80'

    volumes:
      - /opt/apps/config/kheera/dev-config.js:/usr/share/nginx/html/config.js:ro

    networks:
      - app-network

networks:
  app-network:
    external: true
