# Build Stage
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build -- --configuration production --base-href=/

FROM nginx:alpine

COPY --from=build /app/dist/kheera-ui/browser /usr/share/nginx/html

EXPOSE 80
