services:
  kheera-frontend:
    build: .

    container_name: kheera-frontend

    restart: unless-stopped

    ports:
      - '4200:80'

    volumes:
      - /opt/apps/config/kheera/prod-config.js:/usr/share/nginx/html/config.js:ro

    networks:
      - app-network

networks:
  app-network:
    external: true
